home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# Create your urls here.
app_name = 'home'

urlpatterns = [
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name="home/change_password.html",
            success_url='/'
        ),  
        name="change_password"
    ),# 20210415
    # path("secretPage/", views.secretPage, name="secretPage"),  #20210408
    path("register/", views.register, name="register"),  # 20210325
    path('social/', views.socialview, name='social'),
    path('about/', views.aboutview, name='about'),
    path('contact/', views.contact, name='contact'),
    path('', views.index, name='index'),
]

libshopapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

# from . import views
# from home.views import secretPage

urlpatterns = [
    # path('registration/', include('django.contrib.auth.urls')),
                  #
    path('store/', include('store.urls', namespace='store')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# app_name # 後台

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'), name='auth'),
    path('accounts/', include('django.contrib.auth.urls'), name='register'),
    # path('accounts/', include('accounts.urls')),  # new 20210323
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # 參考資料: https://github.com/mitchtabian/CodingWithMitch-Blog-Course/blob/Reset-Password-and-Change-Password-(Django)/src/mysite/urls.py

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),  # 寫信箱郵件
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),#我們已通過電子郵件發送給您有關設置密碼的說明。 如果幾分鐘後還沒到達，請檢查您的垃圾郵件文件夾。
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),#密碼已更改！
    # path("secretPage/", views.secretPage.as_view(), name="secretPage"),  # 20210408

# 1.submit email from                      //PasswordResetView.as_view() //填好註冊登記的 20210412
#     path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
# 2.email sent success message             //PasswordResetDoneView.as_view() //信箱郵件成功進入user 信箱
#     path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
# 3.link to password Reset from in email   //PasswordResetConfirmView.as_view() //給予連結請user 點入更改密碼
#     path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
# 4.password successfully changed message  //PasswordResetCompleteView.as_view() //密碼成功更改，user 確認更改好了
#     path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

posts/urls.py
from django.urls import path

from . import views

# Create your urls here.
app_name = 'posts'

urlpatterns = [
        # path('aaa/', views.aaa, name='aaa'),
        path('list', views.posts_list, name='list'),#http://127.0.0.1:8000/posts/list
        path('create/', views.posts_create, name='create'),#http://127.0.0.1:8000/posts/create
        path('<int:id>/detail', views.posts_detail, name='detail'), #http://127.0.0.1:8000/posts/9/
        path('<int:id>/update/', views.posts_update, name='update'),#http://127.0.0.1:8000/posts/3/edit/
        path('<int:id>/delete/', views.posts_delete, name='delete'),#http://127.0.0.1:8000/posts/delete
    ]

posts/models.py
from django.db import models

from django.conf import settings
from django.urls import reverse
from django.db.models.signals import pre_save

from django.utils import timezone
from django.utils.text import slugify


# Create your models here.
# Model Managers & Handling Drafts
# queryset_list = Post.objects.all() -> 演變為查詢集
# queryset_list = Post.objects.create(user=user, title="some Time") -> 運用建立來給予東西
class PostManagers(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManagers, self).all() #下面意思是喬遷好 本身有覆蓋功能->覆蓋view 48行那段
        return super(PostManagers, self).filter(draft=False).filter(publish__lte=timezone.now())


# 這算是進階的把檔案歸類好分辨這樣 QWQ
def images(instance, filename):
    filebase, extension = filename.split(".")
    return "%s/%s" % (instance.id, filename)
    # return "%s/%s.%s" % (instance.id, instance.id, extension)


User = settings.AUTH_USER_MODEL
class Post(models.Model):
    user = models.ForeignKey(User, default=1, db_constraint=False, on_delete=models.CASCADE)  # blank=True, null=True =>默認=1
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True, null=False, max_length=10)
    img = models.ImageField(
        upload_to=images,
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field"
    )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    file = models.FileField(upload_to='files', null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    # Item Publish Date & Draft
    draft = models.BooleanField(default=False)
    publish = models.DateTimeField(auto_now=False, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    posts = PostManagers()  # or can fix:　people  = models.Manager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'id': self.id})  # 改變會變成1-5-6 效果
        # return reverse('posts:detail', kwargs={'slug': self.slug})

    class Mate:
        ordering: ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    # slug = slugify(instance.title)
    # # Tesla item 1 -> "Tesla-item-1"
    # exists = Post.objects.filter(slug=slug).exists()
    # if exists:
    #     # slug = "%s-%s" %(slugify(instance.title), instance.id)
    #     slug = "%s-%s" %(slug, instance.id)
    #     instance.slug = slug


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from posts.models import Post


class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'id',
            'title',
            'slug',
            'img',
            'file',
            'content',
            'draft',
            'publish',
        ]

posts/views.py
from urllib.parse import quote_plus

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

from .models import Post
from .forms import PostForms

# Create your views here.

def posts_create(request):  # retrieve
    # basic use permissions 基本使用權限; 添加這個但是在無痕中會出現404
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    # if not request.user.is_authenticated:
    #     raise Http404

    form = PostForms(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # Associate User to Post with a Foreign Key #關聯用戶以外鍵進行發布
        # instance.user = request.user
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        messages.error(request, "Not successfully Created")
    context = {
        'form': form,
    }
    return render(request, 'posts/post_form.html', context)

def posts_detail(request, id=None):  # retrieve
    instance = get_object_or_404(Post, id=id)
    # instance = get_object_or_404(Post, slug=slug)
    # 這要強調是 工作人員可子看見 "草稿" 非工作人員或是超級用戶會排除 我就不用擔心
    # if instance.draft: #出現草稿就這樣填上 下面是日期可以了解下
    if instance.publish > timezone.now() or instance.draft: #填上一些日期部分做區分
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404

    share_string = quote_plus(instance.content)
    context = {
        'title': instance.title,
        'instance': instance,
        'share_string': share_string,
    }
    return render(request, 'posts/post_detail.html', context)

# from operator import attrgetter
# def home_screen_view(request):
#     context = {}
#     query = ""
#     if request.GET:
#         query = request.GET['q']
#         context['query'] = str(query)
#     list_posts = sorted(posts_list(query), key=attrgetter('date_updated'), reverse=True)
#     context['list_posts'] = list_posts
#     return render(request, "posts/post_list.html", context)

# paginator / odel Managers & Handling Drafts /
def posts_list(request):  # list items
    # Manager 管理員類型觀看 (選擇隱藏或是公開草稿)
    today = timezone.now().date()
    # queryset_list = Post.objects.filter(draft=False).filter(publish__lte=timezone.now()) #.all() #.order_by("-timestamp") 運用filter意思是未來文章/草稿不會出現 -> Model Managers & Handling Drafts
    queryset_list = Post.posts.active() #.order_by("-timestamp") 運用filter意思是未來文章/草稿不會出現 -> Model Managers & Handling Drafts
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.posts.all()

    # search 搜索list內資訊
    query = request.GET.get("q") #.split(" ")# python install 2020 => [python, install, 2020]
    if query:
        queryset_list = queryset_list.filter(
            # title__icontains=query)
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(timestamp__icontains=query)
            # Q(user_id__first_name__icontains=query) |
        ).distinct()

    # paginator 分頁
    # paginator = Paginator(queryset_list, 35)  # Show 25 contacts per page.

    # page_reguest_var = "page"
    # page = request.GET.get(page_reguest_var)
    #
    # try:
    #     queryset = paginator.page(page)
    # except PageNotAnInteger:
    #     #     if page is not an intrger, deliver first page.
    #     queryset = paginator.page(1)
    # except EmptyPage:
    #     #     if page out of range(e.g. 9999), deliver last page of request
    #     queryset = paginator.page(paginator.num_pages)

    context = {
        # 'object_list': queryset,
        # 'title': 'List',
        # 'page_reguest_var': page_reguest_var,
        # 'today': today,
    }
    return render(request, 'posts/post_list.html', context)

def posts_update(request, id=None):
    # basic use permissions 基本使用權限
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, id=id) #抓出第幾個單頁
    form = PostForms(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        # message success
        messages.success(request, "<a href='#>Item</a> Saved", extra_tags='html_safe')
        # messages.success(request, "Successfully Item Saved")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title': instance.title,
        'instance': instance,
        'form': form,
    }
    return render(request, 'posts/post_form.html', context)

def posts_delete(request, id=None):
    # basic use permissions 基本使用權限
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "successfully deleted")
    return redirect("posts:list")

templates/posts/post_detail.html
{% extends "base_generic.html" %}
{% block content %}
    {% load urlify %}
    <body>

    <h5 style="color: greenyellow;">笨蛋</h5>
    <div class="col-sm-6">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {% if "html_safe" in message.tags %} {{ message |safe }} {% else %} {{ message }} {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class='col-sm-6 col-sm-offset-3'>
        {% if instance.img %}
            <img src="{{ instance.img.url }}" alt="" class="img-responsive">
        {% endif %}
        <h1>{{ title| truncatechars:10 }}
            <small>{% if instance.draft %}<span style="color: red">Draft</span>{% endif %}&nbsp;{{ instance.publish }}</small>
            {#            <small>{{ instance.publish }}</small>   / {{ instance.timestamp | timesince }}#}
        </h1>

        {#        {% if user.get_full_name %}#}
        <p>Author : {{ user.get_full_name }}</p>
        {#        {% endif %}#}

        {#        {{ share_string }} {# title 概念 #}
        {{ instance.id }}<br>
        {% url 'posts:detail' id=instance.id %}<br>
        {#    <a href="{{ instance.get_absoulute_url }}"></a>{{ instance.title }}<br>#}

        <p>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                Facebook
            </a>
            {#        <a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}">#}
            {#            Twitter#}
            {#        </a>#}
            <a href="https://twitter.com/home?status={{ instance.content | truncatechars:20 | urlify }}%20{{ request.build_absolute_uri }}">
                Twitter
            </a>
            <a href='https://plus.google.com/share?url=http://codingforentrepreneurs.com'>Google+</a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source=http://swiftforentrepreneurs.com/">
                Linkedin
            </a>
            <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}.">Reddit</a>
            <a data-pin-do="buttonBookmark"
               href="//www.pinterest.com/pin/create/button/?url={{ request.build_absolute_uri }}">
                <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png"/>
            </a>
        </p>
        {{ instance.updated }}<br>
        {{ instance.timestamp }}<br>

        <div class="row">
            <div class="col-sm-12 col-sm-offset-1">
                {{ instance.content|linebreaks|truncatechars:20 }}<br>
{#                {{ instance.content|linebreaks|truncatechars:10|urlify }}<br>#}
{#                {{ share_string | truncatechars:10 }}#}
{#              {{ instance.content | linebreaks | truncatechars:20 }}<br>#}
                <hr>
                <br>
                {# <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">分享</a></div>#}
                <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width=""
                     data-layout="standard" data-action="like" data-size="small" data-share="true"></div>
                <div class="fb-comments" data-href="{{ request.build_absolute_uri }}"
                     data-numposts="5" data-width=""></div>
            </div>
        </div>

    </div>


    <a href="{% url 'posts:update' id=instance.id %}">Edit/update Post</a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'posts:delete' id=instance.id %}">Del Post</a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'posts:list' %}">Post</a>
    </body>

{% endblock %}

templates/posts/post_form.html
<body>
<h1>Form</h1>
<form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Save Post">
</form>
</body>

templates/posts/post_list.html
{% extends "base_generic.html" %}
{% block content %}
    {% load static %}

    {#    {% if post_list %}#}
    <div class="col-sm-12">
        <a href="{% url 'home:index' %}" class="pt-5 text-danger bg-dark text-decoration-none">返回首頁</a>
    </div>
    <div class='col-sm-6 col-sm-offset-3'>
        <h1> {{ title }} is working! </h1>

        <form method='GET' action=''>{# 不要亂添加 #}
            {% csrf_token %}
            <a href="{% url 'posts:create' %}">Create Post</a>
            <br><br>
            <input type='text' name='q' placeholder='Search Posts' value='{{ request.GET.q }}' id="id_q"
                   class=""/>{# form-control #}
            <input type='submit' value='Search'/>
        </form>

        {#{% url 'detail' id=obj.id %}#}
        {% for obj in object_list %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                        <h1>{{ obj.id }}<br></h1>
                        {% if obj.img %}
                            <img src="{{ obj.img.url }}" class="img-responsive" alt="">
                        {% endif %}
                        /posts/id

                        <div class="py">
                            {% if obj.draft %}
                                <h5>Staff Only: Draft</h5>
                                {% if obj.publish > today %}
                                    <h5>STAFF ONLY: Future Post </h5>
                                {% endif %}
                            {% endif %}
                            <h3>
                                <a href="{{ obj.get_absolute_url }}">{{ obj.title|truncatechars:10 }}<br><small>{{ obj.publish }}ago</small></a>
                            </h3>
                            {#                            {{ obj.publish }} ago  {{ obj.timestamp|timesince }} ago#}
                            {% url "posts:detail" id=obj.id %}
                            {# 1.  id=obj.id => /posts/id  2."{% url 'detail' id=obj.id %}"   3. 因get_absoulute_url return reverse('posts:detail')  so  "{% url 'post:detail' id=obj.id %}"#}
                            {% if user.get_full_name %}
                                <p>Author: {{ user.get_full_name }}</p>
                            {% endif %}
                            <a href="{{ obj.get_absolute_url }}">{{ obj.title | truncatechars:20 }}</a><br>
                            {#<a href="{% url 'posts:detail' id=obj.id %}">{{ obj.title }}<br></a>#}
                            {{ obj.content | linebreaks | truncatechars:80 }}<br>
                            {{ obj.timestamp }}<br>
                            {{ obj.updated }}<br>

                            {#                            {% if obj.img %}#}
                            {#                                <img src="{{ obj.img.url }}" alt="" class="img-responsive">#}
                            {#                            {% endif %}#}
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}

        {#--pagination--#}
        <div class="pagination">
            <span class="step-links">
                {% if object_list.has_previous %}
                    <a href="?{{ page_reguest_var }}=1">&laquo; first</a>
                    <a href="?{{ page_reguest_var }}=

                            {{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </span>

                {% if object_list.has_next %}
                    <a href="?{{ page_reguest_var }}=
                            {{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                    <a href="?{{ page_reguest_var }}={{ object_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        {# /* --pagination--#}

    </div>

    {#    {% else %}#}
    {#    <div class="container">#}
    {#        <div class="row">#}
    {#            <div class="card m_auto">#}
    {#                <div class="card-body mt-2 mb-2">#}
    {#                    <h2 class="card-title">NO RESULTS</h2>#}
    {#                    <div class="card-text">There were no results matching your search: "{{ query }}".</div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    {#    {% endif %}#}

{% endblock content %}

<script type="text/javascript">
    document.getElementById("id_q").value = "{{query}}"
</script>

templates/posts/post_list2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'template.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="#">Bootstrap</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#">React</a>
              </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">

      <h3>Filter Journals</h3>
      <form method="GET" role="search" action="{% url 'search' %}" target="_blank"> {# {% url 'search_results' %}   {{ productSearch }}#}
        <div class="form-row">
            <div class="form-group col-12">
{#                name: django #}
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" role="search" type="text" name="q" placeholder="Title product title(包含)..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="id_exact" placeholder="ID exact(精確)..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="title_or_author" placeholder="Title or author..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-2 col-lg-2">
            <label for="viewCountMin">Minimum View Count</label>
            <input type="number" min=0 class="form-control" id="viewCountMin" placeholder="0" name="view_count_min">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="viewCountMax">Maximum View Count</label>
            <input type="number" min=0 class="form-control" id="viewCountMax" placeholder="10000?" name="view_count_max">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="publishDateMin">Publish date minimum</label>
            <input type="date" class="form-control" id="publishDateMin" name="date_min">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="publishDateMax">Publish date maximum</label>
            <input type="date" class="form-control" id="publishDateMax" name="date_max">
          </div>
          <div class="form-group col-md-4">
            <label for="category">Category</label>
            <select id="category" class="form-control" name="category">
              <option selected>Choose...</option>
              {% for cat in categories %}
              <option value="{{ cat }}">{{ cat }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="reviewed" name="reviewed">
            <label class="form-check-label" for="reviewed">
              Reviewed
            </label>
          </div>
        </div>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="notReviewed" name="notReviewed">
            <label class="form-check-label" for="notReviewed">
              Not reviewed
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>

      <hr/>
{# filter #}
      <div class="row">
        <ul>
          {% for journal in queryset %}
            <li>
              {{ journal.title }}
              <span>Author: {{ journal.author.name }}</span>
              <span>
                {% for cat in journal.categories.all %}
                  {{ cat }}
                {% endfor %}
              </span>
              <span>Publish date: {{ journal.publish_date }}</span>
              <span>View count: {{ journal.views }}</span>
              <span>Reviewed: {{ journal.reviewed }}</span>
            </li>
            <hr />
          {% endfor %}
        </ul>
      </div>

    </main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>