home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# Create your urls here.
app_name = 'home'

urlpatterns = [
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name="home/change_password.html",
            success_url='/'
        ),  
        name="change_password"
    ),# 20210415
    # path("secretPage/", views.secretPage, name="secretPage"),  #20210408
    path("register/", views.register, name="register"),  # 20210325
    path('social/', views.socialview, name='social'),
    path('about/', views.aboutview, name='about'),
    path('contact/', views.contact, name='contact'),
    path('', views.index, name='index'),
]

libshopapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

# from . import views
# from home.views import secretPage

urlpatterns = [
    # path('registration/', include('django.contrib.auth.urls')),
                  #
    path('store/', include('store.urls', namespace='store')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# app_name # 後台

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'), name='auth'),
    path('accounts/', include('django.contrib.auth.urls'), name='register'),
    # path('accounts/', include('accounts.urls')),  # new 20210323
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # 參考資料: https://github.com/mitchtabian/CodingWithMitch-Blog-Course/blob/Reset-Password-and-Change-Password-(Django)/src/mysite/urls.py

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),  # 寫信箱郵件
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),#我們已通過電子郵件發送給您有關設置密碼的說明。 如果幾分鐘後還沒到達，請檢查您的垃圾郵件文件夾。
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),#密碼已更改！
    # path("secretPage/", views.secretPage.as_view(), name="secretPage"),  # 20210408

# 1.submit email from                      //PasswordResetView.as_view() //填好註冊登記的 20210412
#     path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
# 2.email sent success message             //PasswordResetDoneView.as_view() //信箱郵件成功進入user 信箱
#     path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
# 3.link to password Reset from in email   //PasswordResetConfirmView.as_view() //給予連結請user 點入更改密碼
#     path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
# 4.password successfully changed message  //PasswordResetCompleteView.as_view() //密碼成功更改，user 確認更改好了
#     path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

home/models.py
from django.db import models
from django.dispatch import receiver
from django.conf import settings
from django.db.models.signals import (
    pre_save,  # 那是預先保存好的，所以預先保存很像後期保存
    post_save,
)

# Create your models here.

# test 03/30/2021
User = settings.AUTH_USER_MODEL


class LoggedInUser(models.Model):
    user = models.OneToOneField(User, related_name='logged_in_user', on_delete=models.CASCADE)
    session_key = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return self.user.username


@receiver(pre_save, sender=User)
def user_pre_save_receiver(sender, instance, *args, **kwargs):
    """
    before saved in the database
    """
    # print(args, kwargs)
    print(instance.username, instance.id)  # None


#     trigger pre_save
#     instance.save() # <-- DONT DO　THIS -> 加了save 就出現錯誤但是可以單一加入pre_save and post_save 2選1
#     trigger post_save

# pre_save.connect(user_pre_save_receiver, sender=User)

@receiver(post_save, sender=User)
def user_post_save_receiver(sender, instance, created, *args, **kwargs):
    """
    after saved in the database
    """
    # print(args, kwargs)
    if created:
        print('send email to ', instance.username)
        # trigger(觸發板機) pre_save
        # instance.save() 加了save 就出現錯誤但是可以單一加入pre_save and post_save 2選1
        # trigger post_save
    else:
        print(instance.username, 'was just saved!!!')

# pre_save.connect(user_pre_save_receiver, sender=User)

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# Create your forms here.

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    # template_name = '/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

# class RegisterForm(UserCreationForm):#20210325
#     # email = forms.EmailField(required=True)
#     first_name = forms.CharField(
#         max_length=30,
#         required=False,
#         help_text='*必填。郵寄、付款需真實姓名。',
#         label="名字",
#     )
#     last_name = forms.CharField(
#         max_length=30,
#         required=False,
#         help_text='*必填。郵寄、付款需真實姓名。',
#         label="姓氏",
#     )
#     email = forms.CharField(
#         required=True,
#         max_length=254,
#         help_text='*必填。 通知有效的電子郵件地址。',
#         label="電子郵件",
#     )
#
#     class Meta:
#         model = User
#         fields = (
#             'username',
#             'last_name',
#             'first_name',
#             'email',
#             'password1',
#             'password2',
#         ) #, 'first_name', 'last_name'
#
#     def save(self, commit=True):
#         user = super(RegisterForm, self).save(commit=False)
#         user.username = self.cleaned_data['username']
#         user.first_name = self.cleaned_data['first_name']
#         user.last_name = self.cleaned_data['last_name']
#         user.email = self.cleaned_data['email']
#
#         if commit:
#            user.save()
#         return user

# def clean_username(self):
#     username = self.cleaned_data['username'].lower()
#     r = User.objects.filter(username=username)
#     if r.count():
#         raise ValidationError("Username already exists")
#     return username
#
# def clean_email(self):
#     email = self.cleaned_data['email'].lower()
#     r = User.objects.filter(email=email)
#     if r.count():
#         raise ValidationError("Email already exists")
#     return email
#
# def clean_password2(self):
#     password1 = self.cleaned_data.get('password1')
#     password2 = self.cleaned_data.get('password2')
#
#     if password1 and password2 and password1 != password2:
#         raise ValidationError("密碼不匹配")
#
#     return password2

home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import send_mail

from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login, authenticate

from django.contrib.auth.models import User #20210414
# from .forms import RegisterForm
from home.forms import (
    RegistrationForm,
    EditProfileForm,
)
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def email(request):
    subject = '感謝您註冊到我們的網站 / Thank you for registering to our site'
    message = '對我們來說意味著一個世界 / it  means a world to us '
    email_from = settings.EMAIL_HOST_USER
    recipient_list = ['receiver@gmail.com', ]  # recipient_list:收件人清單
    send_mail(subject, message, email_from, recipient_list)
    return redirect('redirect to a new page') #重定向到新頁面


# def secretPage(request):
#     context = {}
#     return render(request, 'registration/secretPage.html', context)


def register(request):  # 20210325
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        print("Errors", form.errors)
        if form.is_valid():
            form.save()
            #
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')

            user = authenticate(username=username, password=raw_password, first_name=first_name, last_name=last_name,
                                email=email)
            login(request, user)
            #
            print('user created!!!')
            messages.success(request, 'Account created successfully')
            return render(request, 'index.html')
        else:
            messages.success(request, 'Account created " NOT " successfully')
            context = {'form': form}
            return render(request, 'registration/signup.html', context)
    else:
        form = RegistrationForm()
        context = {'form': form}
        return render(request, 'registration/signup.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('home:view_profile'))
        else:
            return redirect(reverse('home:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'home/change_password.html', args)

@login_required
@csrf_protect
def index(request):
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'title': '首頁',
        'num_visits': num_visits,
    }
    # return HttpResponse("hello world!")
    # return render(request, 'index.html')
    # return render(request, 'registration/login.html')
    # setting = Setting.objects.get(pk=1)
    return render(request, 'index.html', context=context)


def contact(request):
    # return HttpResponse("hello world!")
    return render(request, 'home/contact.html')


def aboutview(request, *args, **kwargs):
    my_context = {
        "my_text": "this is about us",
        "my_num": 123,
        "my_list": ["左三圈", 456, 7899],
    }
    return render(request, "home/about.html", my_context)


def socialview(request, *args, **kwargs):
    return HttpResponse("<h5> Socail Page </h5>")

templates/home/about.html
; {% extends "base_generic.html" %}

<title>{% block title %} About page{% endblock %}</title>

{% block content %}
<h1>About</h1>
<p>this is a template</p>
    {{ my_text }}, {{ my_num }}, {{ my_list }}
{% endblock content %}

templates/home/change_password.html
{% extends 'base_generic.html' %}
{% block title %}Change Password...{% endblock %}
{% block content %}

    <div class="container">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Change Password</button>
            </form>
        </div>
        <br>
    </div>

{% endblock %}

templates/home/controlSidebar.html
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <h1>123</h1>
</aside>
<!-- /.control-sidebar -->

templates/home/edit_profile.html
{% extends 'base_generic.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

templates/home/footer.html
{% load static %}
<!-- Main Footer -->
{#<footer id="footer">#}
{#    <p class="copyright text-white-50" style="font-size: 10px;">Copyright&copy;2020#}
{#        <strong style="font-size: 12px">#}
{#            <a href="http://adminlte.io">臺灣總代理-群光電子股份有限公司</a>#}
{#        </strong>BALMUDA INC. ALL RIGHTS RESERVED#}
{#        <div class="float-right d-none d-sm-inline-block" style="font-size: 10px">#}
{#            <b class="text-secondary">Designed by</b><a rel="nofollow" href="#">&nbsp;&nbspGeorgia</a>#}
{#        </div>#}
{#    </p>#}
{#    <p class="copyright">Copyright &copy; BALMUDA INC. ALL RIGHTS RESERVED#}
{#    <br>Designed by <a rel="nofollow" href="#">臺灣代理-群光電子股份有限公司</a>#}
{#</p>#}
{#</footer>#}


<footer class="main-footer">
    <strong>Copyright ©2020<a href="#"></a>臺灣總代理-群光電子股份有限公司</strong>
    BALMUDA INC. ALL RIGHTS RESERVED.
    <div class="float-right d-none d-sm-inline-block">
        <b>Designed by </b> Georgia
    </div>
</footer>

templates/home/head.html
{% load static %}{#只有這邊才需要這個 ，還有在<head> </head> 裡面才需要#}
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="{% static 'home/vendor/plugins/fontawesome-free/css/all.min.css' %}">
<!-- IonIcons -->
{#<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">#}
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'home/vendor/dist/css/adminlte.min.css' %}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<link rel="stylesheet" href="http://apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}">

{# ------------------------------------order.html 套件 start ---------------------------------#}
<link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/20.1.4/css/dx.common.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/20.1.4/css/dx.light.css"/>
{# ------------------------------------order.html 套件 end ---------------------------------#}


<link rel="stylesheet" href="{% static 'home/style/css/style.css' %}">

templates/home/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'home:index' %}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'home:contact' %}" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        {% csrf_token %}
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        {#        <i class="ion-android-cart" style="font-size: 18px"></i>#}
        {#        <i class="ion-android-person" style="font-size: 18px"></i>#}
        {#        <i class="ion-android-settings" style="font-size: 18px"></i>#}

        {#        <i class="ion-log-in" style="font-size: 18px"></i>#}
        {#        <i class="ion-log-out" style="font-size: 18px"></i>#}

        {#        <i class="ion-social-facebook" style="font-size: 18px"></i>#}
        {#        <i class="ion-social-instagram" style="font-size: 18px"></i>#}
        {#        <i class="ion-social-yotube" style="font-size: 18px"></i>#}
        {#        <i class="ion-email" style="font-size: 18px"></i>#}
        {#        <i class="ion-ios-telephone" style="font-size: 18px"></i>#}

        {#   額外補充 START    -----#}
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-android-settings" style="font-size: 18px"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-social-facebook" style="font-size: 18px"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-social-instagram" style="font-size: 18px"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-social-youtube" style="font-size: 18px"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-email" style="font-size: 18px"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-ios-telephone" style="font-size: 18px"></i>
            </a>
        </li>
{#        <li class="nav-item d-none d-sm-inline-block">#}
{#            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">#}
{#                <i class="ion-document-text" style="font-size: 18px"></i>#}
{#            </a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">#}
{#                <i class="ion-android-person" style="font-size: 18px"></i>#}
{#            </a>#}
{#        </li>#}
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="ion-android-cart" style="font-size: 18px"></i>
            </a>
        </li>
        {#   額外補充 END    -----#}
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static 'home/vendor/dist/img/user1-128x128.jpg' %}" alt="User Avatar"
                             class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static 'home/vendor/dist/img/user8-128x128.jpg ' %}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static 'home/vendor/dist/img/user3-128x128.jpg ' %}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

templates/home/profile.html
{% extends 'base_generic.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %}
</div>

{% endblock %}

templates/home/scripts.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'home/vendor/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'home/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/vendor/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- AdminLTE -->
<script src="{% static 'home/vendor/dist/js/adminlte.js' %}"></script>
<script src="http://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'home/vendor/plugins/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'home/vendor/dist/js/demo.js' %}"></script>
<script src="{% static 'home/vendor/dist/js/pages/dashboard3.js' %}"></script>

{# ------------------------------------order.html 套件 start ---------------------------------#}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>window.jQuery || document.write(decodeURIComponent('%3Cscript src="js/jquery.min.js"%3E%3C/script%3E'))</script>
<script src="https://cdn3.devexpress.com/jslib/20.1.4/js/dx.all.js"></script>
{# ------------------------------------order.html 套件 end ---------------------------------#}

<!-- Myself Scripts -->
<script src="{% static 'home/style/js/style.js' %}"></script>
<script src="{% static 'home/style/js/cart.js' %}"></script>