home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# Create your urls here.
app_name = 'home'

urlpatterns = [
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name="home/change_password.html",
            success_url='/'
        ),  
        name="change_password"
    ),# 20210415
    # path("secretPage/", views.secretPage, name="secretPage"),  #20210408
    path("register/", views.register, name="register"),  # 20210325
    path('social/', views.socialview, name='social'),
    path('about/', views.aboutview, name='about'),
    path('contact/', views.contact, name='contact'),
    path('', views.index, name='index'),
]

libshopapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

# from . import views
# from home.views import secretPage

urlpatterns = [
    # path('registration/', include('django.contrib.auth.urls')),
                  #
    path('store/', include('store.urls', namespace='store')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# app_name # 後台

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'), name='auth'),
    path('accounts/', include('django.contrib.auth.urls'), name='register'),
    # path('accounts/', include('accounts.urls')),  # new 20210323
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # 參考資料: https://github.com/mitchtabian/CodingWithMitch-Blog-Course/blob/Reset-Password-and-Change-Password-(Django)/src/mysite/urls.py

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),  # 寫信箱郵件
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),#我們已通過電子郵件發送給您有關設置密碼的說明。 如果幾分鐘後還沒到達，請檢查您的垃圾郵件文件夾。
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),#密碼已更改！
    # path("secretPage/", views.secretPage.as_view(), name="secretPage"),  # 20210408

# 1.submit email from                      //PasswordResetView.as_view() //填好註冊登記的 20210412
#     path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
# 2.email sent success message             //PasswordResetDoneView.as_view() //信箱郵件成功進入user 信箱
#     path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
# 3.link to password Reset from in email   //PasswordResetConfirmView.as_view() //給予連結請user 點入更改密碼
#     path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
# 4.password successfully changed message  //PasswordResetCompleteView.as_view() //密碼成功更改，user 確認更改好了
#     path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

posts/urls.py
from django.urls import path

from . import views

# Create your urls here.
app_name = 'posts'

urlpatterns = [
        # path('aaa/', views.aaa, name='aaa'),
        path('list', views.posts_list, name='list'),#http://127.0.0.1:8000/posts/list
        path('create/', views.posts_create, name='create'),#http://127.0.0.1:8000/posts/create
        path('<int:id>/detail', views.posts_detail, name='detail'), #http://127.0.0.1:8000/posts/9/
        path('<int:id>/update/', views.posts_update, name='update'),#http://127.0.0.1:8000/posts/3/edit/
        path('<int:id>/delete/', views.posts_delete, name='delete'),#http://127.0.0.1:8000/posts/delete
    ]

store/urls.py
from django.urls import path
from . import views

# Create your urls here.
# http://127.0.0.1:8000/accounts/logout/
app_name = 'store'

urlpatterns = [
    # Leave as empty string for base url
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),

    path('create/', views.productCreate, name='create'),
    path('<int:id>/', views.productDetail, name='detail'),
    path('<int:id>/update/', views.productUpdate, name='update'),
    # path('changePassword/', views.changePassword, name='changePassword'),
    path('<int:id>/delete/', views.productDelete, name='delete'),

    path('checkout/', views.checkout, name='checkout'),

    path('update_item/', views.updateItem, name='update_item'),
    # path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),

    path('searchbar/', views.searchbar, name='searchbar'),




]

store/forms.py
from django import forms

from .models import Product, RegistrationData


class ProductForms(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'price',
            'draft',
            'digital',
            'image',
            'width_field',
            'height_field',
            'content',
        ]


class RegistrationModelProductForm(forms.Form):
    title = forms.CharField(label='',
                            widget=forms.TextInput(attrs={"placeholder": "Your title"}))
    email = forms.EmailField()
    description = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Your description",
                "class": "new-class-name two",
                "id": "my-id-for-textarea",
                "rows": 20,
                'cols': 120
            }
        )
    )
    price = forms.DecimalField(initial=199.99)

    # class Meta:
    #     model = RegistrationData
    #     fields = [
    #         'email',
    #     ]
    #     widgets = {
    #         'email':forms.TextInput(attrs={
    #             'class':'form-control',
    #             'placeholder':'email',
    #         }),
    #     }
    # def clean_email(self, *args, **kwargs):
    #     email = self.clean_data.get("email")
    #     if not email.endswith("gmail"):
    #         raise forms.ValidationError("this is not a valid email")
    #     return email
    #
    # def clean_title(self, *args, **kwargs):
    #     title = self.clean_data.get("title")
    #     if "CEF" in title:
    #     if not "CEF" in title:
    #         return title
    #     else:
    #         return title
    #         or
    #         raise forms.ValidationError("This is not a valid title")

store/views.py
import datetime
import json

from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect

from .forms import ProductForms
from store.models import *
from .utils import cartData, guestOrder
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)
from django.utils import timezone


def productCreate(request):
    # if not request.user.is_staff or not request.user.is_superuser:
    #     raise Http404
    form = ProductForms(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()  # 這樣就可以儲存了
        # message success
        messages.success(request,
                         "<div id='msg' class='alert alert-success' role='alert'><strong>Success!</strong>Successfully Created.</div>",
                         extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    # messages.error(request, "Not successfully Created")

    # 購物車購買數量
    data = cartData(request)
    cartItems = data['cartItems']

    context = {
        'title': '建立商品',
        "form": form,
        'cartItems': cartItems,
    }
    return render(request, 'store/form.html', context)


def productUpdate(request, id=None):
    # 購物車購買數量
    data = cartData(request)
    cartItems = data['cartItems']

    # if not request.user.is_staff or not request.user.is_superuser:
    #     raise Http404

    instance = get_object_or_404(Product, id=id)
    form = ProductForms(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        # message success
        # messages.info(request, 'this is a info message!')
        # messages.error(request, 'ERROR!ERROR!')
        # messages.warning(request, 'Be careful!!!')
        messages.success(request,
                         "<div id='msg' class='alert alert-success col-lg-12' role='alert'><strong>Success!</strong>Success Saved for your edit.</div>",
                         extra_tags='html_safe')
        # messages.success(request, "<a href='#'><strong>疑問通知</strong></a> Success Saved thank you for add join", extra_tags='html_safe')
        # messages.success(request,"{% if messages %}<div class='row'><div class='col-sm-6 col-sm-offset-3'>{% for message in messages %}<div class='alert alert-{{ message.tags }} alert-dismissible fade show' role='alert'>{{ message }}<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>{% endfor %}</div></div>{% endif %}", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     #error message success
    #     messages.success(request, "<a href='#'>通知作者</a> 錯誤儲存 ", extra_tags='html_safe')

    context = {
        'title': '商品編輯',
        'instance': instance,
        'form': form,
        'cartItems': cartItems,
    }
    return render(request, 'store/form.html', context)


# def productUpdate(request, id=None):
#     # 購物車購買數量
#     data = cartData(request)
#     cartItems = data['cartItems']
#
#     if request.method == 'POST':
#         form = EditProfileForm(request.POST, instance=request.user)
#
#     instance = get_object_or_404(Product, id=id)
#     form = ProductForms(request.POST or None, instance=instance)
#     if form.is_valid():
#         instance = form.save(commit=False)
#         instance.save()
#         messages.success(request,
#                          "<div id='msg' class='alert alert-success col-lg-12' role='alert'><strong>Success!</strong>Success Saved for your edit.</div>",
#                          extra_tags='html_safe')
#         return HttpResponseRedirect(instance.get_absolute_url())
#
#     context = {
#         'title': '商品編輯',
#         'instance': instance,
#         'form': form,
#         'cartItems': cartItems,
#     }
#     return render(request, 'store/changePassword.html', context)
#

# 更改密碼 PasswordChangeForm
# def changePassword(request):
#     if request.method == 'POST':
#         form = PasswordChangeForm(request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return redirect('account/profile')
#         else:
#             #是密碼更改表單
#             form = PasswordChangeForm()


# def productDelete(request, id=None):


#     if not request.user.is_staff or not request.user.is_superuser:
#         raise Http404
#     instance = get_object_or_404(Product, id=id)
#     instance.delete()
#     messages.success(request, "Successfully deleted")
#     return redirect("store:store")

def productDelete(request, id=None):
    # if not request.user.is_staff or not request.user.is_superuser:
    #     raise Http404
    obj = get_object_or_404(Product, id=id)
    # "POST" request
    if request.method == "POST":
        # confirming del
        obj.delete()
        return redirect('../../')
    context = {
        'title': '刪除商品',
        "object": obj,
    }
    return render(request, 'store/delete.html', context)


def productDetail(request, id=None):
    instance = get_object_or_404(Product, id=id)
    if instance.draft or instance.timestamp > timezone.now():
        # 登入並且是員工狀況下，就會看到草稿中商品，如果不是員工則看不到。
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404

    data = cartData(request)
    cartItems = data['cartItems']

    context = {
        'name': instance.name,
        'instance': instance,
        'cartItems': cartItems
    }
    return render(request, "store/detail.html", context)


def searchbar(request):
    searchNum = Product.objects.all().count()
    data = cartData(request)
    cartItems = data['cartItems']

    if request.method == 'GET':
        searchNum = request.GET.get('search').count
        search = request.GET.get('search')
        product = Product.objects.all().filter(name=search)
        # searchNum = Product.objects.all().count(number=searchNum)

        context = {
            'title': '搜尋商品',
            'searchNum': searchNum,
            'product': product,
            'cartItems': cartItems
        }
        return render(request, 'store/searchbar.html', context)


# -----------------------------------------------------------
def store(request):
    today = timezone.now().date()
    # products = Product.objects.filter(draft=False).filter(timestamp__lte=timezone.now())#all()  # .order_by("-timestamp")
    products = Product.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        products = Product.objects.all()

    paginator = Paginator(products, 25)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    try:
        queryset = paginator.page(page_obj)
    except PageNotAnInteger:
        queryset = paginator.page(1)

    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    #
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {
        'title': '商品首頁',
        # new
        'object_list': queryset,
        'page_obj': page_obj,
        'queryset': queryset,
        #
        "today": today,
        'products': products,
        'cartItems': cartItems,
    }
    return render(request, 'store/store.html', context)


def cart(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'store/cart.html', context)


def checkout(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('付款已提交/Payment submitted..', safe=False)

templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">

                <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>

                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
                        <th><h5>Total:<strong> ${{ order.get_cart_total|floatformat:2 }}</strong></h5></th>
                        <th>
                            <a style="float:right; margin:5px;" class="btn btn-success"
                               href="{% url 'store:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>

            </div>

            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{ item.product.image.url }}"></div>
                        <div style="flex:2"><p>{{ item.product.name }}</p></div>
                        <div style="flex:1"><p>${{ item.product.price|floatformat:2 }}</p></div>
                        <div style="flex:1">
                            <p class="quantity">{{ item.quantity }}</p>
                            <div class="quantity">
                                <img data-product="{{ item.product.id }}" data-action="add"
                                     class="chg-quantity update-cart"
                                     src="{% static  'home/style/images/arrow-up.png' %}">

                                <img data-product="{{ item.product.id }}" data-action="remove"
                                     class="chg-quantity update-cart"
                                     src="{% static  'home/style/images/arrow-down.png' %}">
                            </div>
                        </div>
                        <div style="flex:1"><p>${{ item.get_total|floatformat:2 }}</p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/store/detail.html
{% extends 'store/main.html' %}
{% load static %}
<title>{% block head_title %} {{ instance.name }} | {{ block.super }}{% endblock head_title %}</title>
{#商品名稱=instance.name | 公司名稱=block.super#}
{% block content %}

    <h5 style="color: greenyellow"><br><br></h5>
    {#    <div class="col-sm-6">#}
    {#        {% if messages %}#}
    {#            <ul class="messages" style="list-style:none;">#}
    {#                {% for message in messages %}#}
    {#                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
    {#                        {% if "html_safe" in message.tags %} {{ message |safe }} {% else %}#}
    {#                            {{ message }} {% endif %}#}
    {#                    </li>#}
    {#                {% endfor %}#}
    {#            </ul>#}
    {#        {% endif %}#}
    {#    </div>#}
    <div class='col-sm-6 col-sm-offset-3'>

        {% if instance.user.get_full_name %}
            <p>Author : {{ instance.user.get_full_name }}</p>
        {% endif %}


        {% if instance.image %}
            <img src="{{ instance.image.url }}" alt="" class="img-responsive">
        {% endif %}
        <h1>{{ name| truncatechars:10 }}
            <small>{% if instance.draft %}<span style="color: red">Draft</span>{% endif %}
                &nbsp;{{ instance.timestamp }}</small>
        </h1>
        <h1>{{ name| truncatechars:10 }}
            <small>{{ instance.price }} /元</small>
        </h1>

        <small>{{ instance.content }}</small>
        <small>{{ instance.digital }}</small>

        <p>Author : {{ user }}</p>

        {{ instance.id }}<br>
        {% url 'posts:detail' id=instance.id %}<br>
        <a href="{{ instance.images }}"></a>{{ instance.name }}<br>

        <p>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                Facebook
            </a>
            <a href="https://twitter.com/home?status={{ instance.name | truncatechars:20 }}%20{{ request.build_absolute_uri }}">
                Twitter
            </a>
            <a href='https://plus.google.com/share?url=http://codingforentrepreneurs.com'>Google+</a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source=http://swiftforentrepreneurs.com/">
                Linkedin
            </a>
            <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}.">Reddit</a>
            <a data-pin-do="buttonBookmark"
               href="//www.pinterest.com/pin/create/button/?url={{ request.build_absolute_uri }}">
                <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png"/>
            </a>
        </p>
        <div class="row">
            <div class="col-sm-12 col-sm-offset-1">
                {{ instance.content|linebreaks|truncatechars:20 }}<br>
                <hr>
                <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width=""
                     data-layout="standard" data-action="like" data-size="small" data-share="true"></div>
                {#                    <div class="fb-comments" data-href="{{ request.build_absolute_uri }}"#}
                {#                         data-numposts="5" data-width=""></div>#}
            </div>
        </div>
        <div class='col-sm-6 col-sm-offset-3'>
            FBook留言
        </div>
        <div class='col-sm-6 col-sm-offset-3'>
            {% if user.is_staff %}
                <a href="{% url 'store:update' id=instance.id %}">Edit/update Product</a><br>
                <a href="{% url 'store:delete' id=instance.id %}">Del Product</a><br>
                {#                <a href="{% url 'store:list' %}">Product</a><br>#}
            {% endif %}

        </div>
    </div>


{% endblock %}

templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block head_title %} Ecom 公司 {% endblock head_title %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'home/style/css/main.css' %}">

    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getToken('csrftoken')

        function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if (name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }

            // Return null if not found
            return null;
        }

        var cart = JSON.parse(getCookie('cart'))

        if (cart == undefined) {
            cart = {}
            console.log('Cart Created!', cart)
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)

    </script>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
            </li>
        </ul>

        <div class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <div class="info nav-link d-block" href="{% url 'logout' %}">
                            &nbsp;&nbsp;hi,&nbsp;{{ user.get_username }}<a class="text-white logo"
                                                                           href="{% url 'logout' %}"><b>&nbsp;/登出</b>
                            <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <div class="info nav-link d-block" href="{% url 'login' %}">
                            hi&nbsp;Admin,&nbsp<a class="text-white logo"
                                                  href="{% url 'login' %}"><b>登入</b>
                            <i class="fa fa-sign-in fa-1x" aria-hidden="true"></i></a>
                        </div>
                    </li>
                {% endif %}

            </ul>

            <a href="{% url 'store:cart' %}">
                <img id="cart-icon" src="{% static 'home/style/images/cart.png' %}">
            </a>
            <p id="cart-total">{{ cartItems }}</p>
        </div>

        <div>
            <form role="form" class="form-inline pl-3" action="{% url 'store:searchbar' %}"
                  method="get">{% csrf_token %}
                <input id="id_q" name="search" class="form-control mr-sm-2" type="search" placeholder="搜尋 Search"
                       aria-label="Search" value="{{ request.GET.q }}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

    </div>
</nav>
{#{% include "store" %} 權限遭拒絕室這邊出問題 PermissionError: [Errno 13] Permission denied: 'C:\\Users\\georgiawang\\PycharmProjects\\libshopapp\\templates\\store' #}
<div class="container">
    {% block content %}

    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'home/style/js/cart.js' %}"></script>

</body>
</html>